### ISSUE TITLE
Disabling Correlation Rules leads to duplicating and enabling again

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#13]
When we disable any rules in the `Correlation Rules`, which leads to duplicating them.

**Steps to reproduce:**

1. Create couple of rules in the Correlation Rules
2. Disable them
3. Click on any other element in your test plan
4. Click on `Correlation Recorder` element again
5. You can see the rules got duplicated and enabled again

**Comment by RicardoPoleo** [comment]
Hello @QAInsights, 

Thanks for reporting this bug. We registered it, and we will inform you as soon as we release the patch.

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights,

This issue was resolved in our latest [patch release](https://github.com/Blazemeter/CorrelationRecorder/releases). Please check it out and let us know if you have any problems with it.

 I'll be closing this issue but, as always, don't hesitate to reopen it if the problem persists.

Happy Hacking!

**Comment by QAInsights** [comment]
@RicardoPoleo I tested the patch release 1.1.1, it seems that the issue still persists. Here is the recording [https://share.qainsights.com/llu2K6XR](https://share.qainsights.com/llu2K6XR).
